#!/bin/bash

tar -cvzf sparql-query-bm.tar.gz --exclude "target/" --exclude "*.tar" --exclude "*.gz" --exclude ".svn/" --exclude ".settings/" --exclude ".classpath" --exclude ".DS_Store" --exclude ".project" . 